### PR TITLE
Feature/add indeterminate state

### PR DESCRIPTION
**Pull request by Luiz-N**
This adds the [fa-plus-square-o icon](http://fontawesome.io/icon/plus-square-o/) for when a checkbox is in an [indeterminate state](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate).

screenshot 2017-04-17 16 09 56

Any valid font awesome icon can be switched out if desired.

### CODE REVIEW

**Comment by bvoelker** [comment]
For line thickness consistency we should probably go with just the plus icon "fa-plus"

**Comment by bvoelker** [comment]
Just looking for some doc info before i approve this pr.

**Comment by Luiz-N** [comment]
@bvoelker @brianvoe yeah i'm working on it... having circle ci issues on other PR

**Comment by Luiz-N** [comment]
snapshot of Docs:

screenshot 2017-04-19 09 12 24

**Pull request closed without merging**
